config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end



# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
# Defines the root path route ("/")
# root "articles#index"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: {minimum:6,maximum:100}
  validates :description, presence: true, length: {minimum:6,maximum:200}
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase}
  has_many :articles
  validates :username, presence:true,
            uniqueness: {case_sensitive: false},
            length: {minimum: 3, maximum: 25}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:true,
            uniqueness: {case_sensitive: false},
            length: {maximum: 105},
            format: {with: VALID_EMAIL_REGEX}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def show
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 3)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = User.first
    if @article.save
      flash[:notice] = "Article successfully created"
      redirect_to @article
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article edited successfully"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    if @article.destroy
      flash[:notice] = "Successfully deleted"
    else
      flash[:alert] = "Failed to delete article"
    end
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    (params.require(:article).permit(:title, :description))
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.paginate(page: params[:page], per_page: 3)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User successfully logged in, Welcome #{@user.username} to the Alpha Blog!"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Your account info was successfully edited"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
    @articles = @user.articles.paginate(page: params[:page], per_page: 3)
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80})
    email_address = user.email.downcase
    hash = Digest::SHA256.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container" >
  <% @articles.each do |article| %>
    <div class="row justify-content-center">
      <div class="col-md-6 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <% if article.user %>
              by <%= link_to article.user.username, user_path(article.user)%>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%=link_to article.title, article_path(article),class:"text-success"%> </h5>
            <p class="card-text"><%= truncate article.description, length:100%></p>
            <%=link_to 'View', article_path(article),class:"btn btn-outline-success",type:"button" %>
            <%=link_to 'Edit', edit_article_path(article),class:"btn btn-outline-info",type:"button" %>
            <%=button_to 'Delete', article_path(article), class:"btn btn-outline-danger ml-2",type:"button",method: :delete, form_class: "d-inline"%>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at)%> ago,edited <%=time_ago_in_words(article.updated_at)%> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @article %>
      <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label text-light"%>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded",placeholder: "Title of article"%>
          </div>
        </div>

        <div class="form-group row pt-3 ">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div>

        <div class="form-group row justify-content-center pt-3">
          <%= f.submit class: "btn btn-outline-light btn-lg w-50" %>
        </div>
      <% end %>
    </div >
    <div class="row justify-content-center">
      <div class="col-10 text-center ">
        <%= link_to 'Cancel and return to article listing', articles_path, class: "text-dark" %>
      </div>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
 <h1 class="text-center mt-4">Edit article</h1>
  <%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Articles Listing Page</h1>

<div class="flickr_pagination ">
  <%= will_paginate @articles, :container => false %>
</div>
<%= render 'article' %>
<div class="flickr_pagination mb-3">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
 <h1 class="text-center mt-4">Create new Articles</h1>
  <%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"><%= @article.title %></h2>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          by <%= @article.user.username if @article.user %>
          <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
        </div>
        <div class="card-body">
          <div class="card-text text-left"><%= simple_format(@article.description) %></div>
          <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-outline-info", type: "button" %>
          <%= button_to 'Delete', article_path(@article), class: "btn btn-outline-danger ml-2", type: "button", method: :delete, form_class: "d-inline" %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(@article.created_at) %> ago,
            edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; <%=link_to "Glenn Lloyd Ybañez Jr.","https://www.youtube.com/@PewDiePie", class: "text-white" %></small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Bloggers', users_path, class: "nav-link"  %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Create new Article", new_article_path, class: "dropdown-item"%>
            <%= link_to "View Articles" , articles_path, class: "dropdown-item" %>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Home</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
</head>
<body class="d-flex flex-column">
<%= render 'layouts/navigation' %>
<div id="page-content">
  <%= render 'layouts/messages' %>
  <%= yield %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/about.html.erb
<h1> This is the about page </h1>
<%=link_to 'home',root_path %>

app/views/pages/home.html.erb
 <div class="container" id="home-container">
    <div class="jumbotron text-center text-white">
      <h1 class="display-4">Alpha Blog</h1>
      <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to
        featured content or information.</p>
      <hr class="my-4">
      <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
      <%= link_to 'Sign Up!' , signup_path, class: "btn btn-success btn-lg", role: "button" %>
    </div>
  </div>

app/views/shared/_errors.html.erb
 <% if obj.errors.any? %>
   <div class="alert alert-warning alert-dismissible fade show" role="alert">
     <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <% end %>
  </div>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-9 mt-3">
      <div class="col-10">
        <%= render 'shared/errors', obj: @user %>
        <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
          <div class="form-group row">
            <%= f.label :username, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
              <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter your username" %>
            </div>
          </div>

          <div class="form-group row pt-3 ">
            <%= f.label :email, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
              <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email address" %>
            </div>
          </div>

          <div class="form-group row pt-3 ">
            <%= f.label :password, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
              <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Enter your password" %>
            </div>
          </div>

          <div class="form-group row justify-content-center pt-3">
            <%= f.submit(@user.new_record? ? "Sign up" : "Update Account", class: "btn btn-outline-light btn-lg w-50") %>
          </div>
        <% end %>
      </div>
      <div class="row justify-content-center">
        <div class="col-10 text-center ">
          <%= link_to 'Cancel and return to article listing', articles_path, class: "text-dark" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your account</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha Bloggers</h1>

<div class="flickr_pagination ">
  <%= will_paginate @users, :container => false %>
</div>

<% @users.each do |user| %>
  <div class="row justify-content-center">
    <div class="col-md-6 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          <%= link_to user.username, user %>
        </div>
        <div class="card-body">
          <h5 class="card-title">
            <%= link_to gravatar_for(user, size: 150), user %>
          </h5>
          <p class="card-text"> <%= pluralize(user.articles.count, "article") %></p>
          <%= link_to 'View profile', user, class: "btn btn-outline-success", type: "button" %>
          <%= link_to 'Edit profile', edit_user_path(user), class: "btn btn-outline-info", type: "button" %>
        </div>
        <div class="card-footer text-muted">
          <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
        </div>
      </div>
    </div>
<% end %>
</div>
<div class="row justify-content-center">
  <div class="col-md-6 mt-4 d-flex justify-content-center align-text-center align-content-center">
  </div>
</div>

<div class="flickr_pagination mb-4 ">
  <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign Up</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %></h1>

<%= gravatar_for @user, size: 200 %>

<div class="text-center mt-2">
<%= link_to 'Edit your profile',edit_user_path(@user), class:"btn btn-outline-info" %>
</div>

<h3 class="text-center mt-4">Articles</h3>

<div class="flickr_pagination ">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>